using System.Collections.Generic;
using System.IO;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
namespace GoogleCloudPrintAPI.Model
{

	/// 
	/// <summary>
	/// @author jittagorn pitakmetagoon
	/// @reference
	/// https://developers.google.com/cloud-print/docs/appInterfaces#submit
	/// </summary>
	public class SubmitJob
	{
		/*
		 * - printerid
		 * Unique printer identification (generated by Google Cloud Print). To get valid printer IDs for a given user, retrieve the list of available printers for that Google Account by querying the /search service interface.
		 */

	    /*
		 * - title
		 * Title of the print job, to be used within GCP.
		 */
	    /*
		 * - capabilities
		 * Printer capabilities (XPS or PPD). Each GCP printer has, associated with it, a list of pair-value capabilities representing printer-specific attributes (available printing formats, copy count, etc.) Capabilities for a given printer can be retrieved using the /list service interface. These retrieved capabilities can then be used to specify desired options on the print job (for instance, print 5 copies instead of the default 1, or print duplex instead of single sided).
		 */
		//private String capabilities;
        /*
         * - FileToPrint
         * Document to print.
         */
        /*
         * -contentType
         * Document type. Currently, valid document types are: url, application/pdf, image/jpeg, or image/png. If contentType = url, the URL should point to a publicly accessible page (there should be no necessary authentication, cookies, etc.) The linked resource can be a PDF, JPG, or PNG file, but we recommend PDF for highest fidelity.
         */
	    /*
		 * - tag
		 * One or more tags to add to the print job. You can attach a set of unique tags to a print job, and these will be available to the printer to which the print job is submitted. This feature may be useful if your application both sends and receives print jobs.
		 */

	    public virtual string PrinterId { get; set; }

	    public virtual string Title { get; set; }

	    public virtual Ticket Ticket { get; set; }

        public virtual FileInfo FileToPrint { get; set; }

	    public virtual string ContentType { get; set; }

	    public virtual List<string> Tag { get; set; }
	}

}